on:
  push:
    branches:
      - master
    paths-ignore:
      - './github/workflows/*'
  workflow_dispatch:

env:
  NODE_JS_VERSION: 21
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch repository code
        uses: actions/checkout@v4
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_JS_VERSION }}
      - name: install project dependencies
        run: npm ci
      - name: setup Pages
        uses: actions/configure-pages@v4
      - name: build project
        run: npm run build
      - name: upload built files
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
