on:
  push:
    branches:
      - master
    paths-ignore:
      - './github/workflows/*'
  workflow_dispatch:

env:
  NODE_JS_VERSION: 21
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch repository code
        uses: actions/checkout@v4
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_JS_VERSION }}
      - name: install project dependencies
        run: npm ci
      - name: setup Pages
        uses: actions/configure-pages@v4
      - name: build project
        run: npm run build
      - name: upload built files
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
